import "dotenv/config";
import OpenAI from "openai";

const apiKey = process.env.OPENAI_API_KEY;

if (!apiKey) {
    throw new Error("Missing OpenAI API key. Set OPENAI_API_KEY.");
}

const client = new OpenAI({ apiKey });

const buildFallbackResponse = (message) => `AI Assistant Response

You asked:

"${message}"

The AI service is currently unavailable.
This is a fallback response generated by the application.`;

const getOpenAIAPIResponse = async (message) => {
    try {
        const response = await client.chat.completions.create({
            model: "gpt-4o-mini",
            messages: [
                {
                    role: "user",
                    content: message
                }
            ]
        });

        const reply = response?.choices?.[0]?.message?.content?.trim();

        if (!reply) {
            throw new Error("OpenAI returned an empty response");
        }

        return reply;
    } catch (error) {
        console.error("OpenAI Error:", error);
        return buildFallbackResponse(message);
    }
};

export default getOpenAIAPIResponse;