import "dotenv/config";
import { GoogleGenerativeAI } from "@google/generative-ai";

const apiKey = process.env.GEMINI_API_KEY;

if (!apiKey) {
    throw new Error("Missing GEMINI_API_KEY");
}

const genAI = new GoogleGenerativeAI(apiKey);

const buildFallbackResponse = (message) => `AI Assistant Response

You asked:

"${message}"

The AI service is currently unavailable.
This is a fallback response generated by the application.`;

const getOpenAIAPIResponse = async (message) => {
    try {
        const model = genAI.getGenerativeModel({
            model: "gemini-1.5-flash"
        });

        const result = await model.generateContent(message);
        const response = await result.response;
        const reply = response.text();

        if (!reply) {
            throw new Error("Gemini returned an empty response");
        }

        return reply;
    } catch (error) {
        console.error("Gemini Error:", error);
        return buildFallbackResponse(message);
    }
};

export default getOpenAIAPIResponse;